# Use root/example as user/password credentials
version: '3.9'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - 3306:3306    
    volumes:
      - type: volume
        source: db_cfg
        target: /etc/mysql
      - type: volume
        source: db_data
        target: /var/lib/mysql

volumes:
  db_cfg:
  db_data:

